# Generated by Django 3.2.12 on 2022-02-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210307_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('', 'select type'), ('system admin', 'system admin')], max_length=50, null=True),
        ),
    ]
